### ISSUE TITLE
Automatic Object creation

### ISSUE THREAD

**Issue by kempert** [ioBroker/ioBroker.node-red#101] opened 2020-04-16 08:34 UTC
No Automatic Object creation in the Objects Tab

The object State Changing is litstet in the events.

Node Red is installed on an Multihost Slave at ioBroker.

`

node-red.1 | 2020-04-15 00:45:52.509 | info | (9782) Automatic objects creation is not enabled. You can enable it in the node configuration
-- | -- | -- | --
node-red.1 | 2020-04-15 00:45:32.244 | debug | (9767) 15 Apr 00:45:32 - [info] serial port /dev/ttyACM0 opened at 9600 baud 8N1
node-red.1 | 2020-04-15 00:45:32.173 | debug | (9767) 15 Apr 00:45:32 - [info] Flows gestartet
node-red.1 | 2020-04-15 00:45:32.042 | debug | (9767) 15 Apr 00:45:32 - [info] [inject:Abrufen - PH Wert] Wiederholen = 20000
node-red.1 | 2020-04-15 00:45:31.218 | debug | (9767) 15 Apr 00:45:31 - [info] Flows starten
node-red.1 | 2020-04-15 00:45:30.556 | debug | (9782) statesDB connected
node-red.1 | 2020-04-15 00:45:30.548 | debug | (9782) States connected to redis: 192.168.178.8:9000
node-red.1 | 2020-04-15 00:45:30.468 | debug | (9767) 15 Apr 00:45:30 - [info] Server wird jetzt auf http://192.168.178.7:1881/ ausgeführt.
node-red.1 | 2020-04-15 00:45:29.804 | debug | (9767) 15 Apr 00:45:29 - [info] Flow-Datei: /opt/iobroker/iobroker-data/node-red/projects/Pool-Steuerung-Kemper/flows.json
node-red.1 | 2020-04-15 00:45:29.786 | debug | (9767) 15 Apr 00:45:29 - [info] Aktives Projekt: Pool-Steuerung-Kemper
node-red.1 | 2020-04-15 00:45:29.720 | debug | (9782) States create System PubSub Client
node-red.1 | 2020-04-15 00:45:29.662 | debug | (9782) States create User PubSub Client
node-red.1 | 2020-04-15 00:45:29.454 | debug | (9782) Redis States: Use Redis connection: 192.168.178.8:9000
node-red.1 | 2020-04-15 00:45:29.423 | debug | (9782) objectDB connected
node-red.1 | 2020-04-15 00:45:29.345 | debug | (9782) Objects connected to redis: 192.168.178.8:9001
node-red.1 | 2020-04-15 00:45:28.985 | debug | (9782) Objects client initialize lua scripts
node-red.1 | 2020-04-15 00:45:28.977 | debug | (9782) Objects create User PubSub Client
node-red.1 | 2020-04-15 00:45:28.962 | debug | (9782) Objects create System PubSub Client
node-red.1 | 2020-04-15 00:45:28.905 | debug | (9782) Objects client ready ... initialize now
node-red.1 | 2020-04-15 00:45:27.803 | warn | (9782) no connection to objects DB
node-red.1 | 2020-04-15 00:45:20.274 | debug | (9782) Redis Objects: Use Redis connection: 192.168.178.8:9001
node-red.1 | 2020-04-15 00:45:27.696 | debug | (9767) 15 Apr 00:45:27 - [info] Benutzerverzeichnis: /opt/iobroker/iobroker-data/node-red/
node-red.1 | 2020-04-15 00:45:27.670 | debug | (9767) 15 Apr 00:45:27 - [info] Kontextspeicher: 'default' [ module=memory]
node-red.1 | 2020-04-15 00:45:27.644 | debug | (9767) 15 Apr 00:45:27 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js
node-red.1 | 2020-04-15 00:45:22.633 | debug | (9767) 15 Apr 00:45:22 - [info] Dashboard version 2.20.0 started at /ui
node-red.1 | 2020-04-15 00:45:12.358 | debug | (9767) 15 Apr 00:45:12 - [info] Polymer started at /polymer
node-red.1 | 2020-04-15 00:44:52.114 | debug | (9767) 15 Apr 00:44:52 - [info] Paletten-Nodes werden geladen
node-red.1 | 2020-04-15 00:44:45.643 | debug | 15 Apr 00:44:45 - [info] Linux 4.19.97+ arm LE
node-red.1 | 2020-04-15 00:44:45.643 | debug | (9767) 15 Apr 00:44:45 - [info] Node.js Version: v10.20.1
node-red.1 | 2020-04-15 00:44:45.620 | debug | (9767) 15 Apr 00:44:45 - [info] Node-RED Version: v1.0.5
node-red.1 | 2020-04-15 00:44:45.587 | debug | ===================
node-red.1 | 2020-04-15 00:44:45.587 | debug | Willkommen bei Node-RED!

`
![image](https://user-images.githubusercontent.com/51061932/79433690-bd597080-7fcd-11ea-8026-39f1e5ed85ac.png)
This is the node wich create this error.

- [x] Node-RED version:  1.0.5
- [ ] Node.js version: 10.20.1
- [ ] npm version: 6.14.4
- [ ] Platform/OS: Raspberry Pi B+ (Raspbian Buster)

**Comment by Apollon77** [comment] 2020-04-27 20:38
please check 1.17.1 from GitHub soon

**Comment by Apollon77** [comment] 2020-05-29 22:27
Any Feedback?

**Comment by mickym2** [comment] 2020-07-02 10:05
Since version 1.17.2 and also in version 2.0.0 I have the same problem that I get the info wth automated object creation.

`

node-red.0 | 2020-07-02 12:02:56.917 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
-- | -- | -- | --
node-red.0 | 2020-07-02 12:02:56.848 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.833 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.817 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.805 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.763 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.748 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.691 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.675 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.646 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.633 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.616 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.573 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.489 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.476 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration
node-red.0 | 2020-07-02 12:02:56.447 | info | (11272) Automatic objects creation is not enabled. You can enable it in the node configuration

`

The problem is  -that I don't know which nodes throw this info.

**Comment by mickym2** [comment] 2020-07-10 20:49
I already switched all iobroker-out nodes to autoCreate="false", but I have still a lot of this entries in the log. Any idea??? - I already installed version 2.0.0

**Comment by Apollon77** [comment] 2020-07-10 21:36
Ääähm ... the error exactly happens when it is turned off ... In fact turn it on and check if a new object is created then you know which object is the reason.

Could it be that you use objects IDs that do not comply with name.X.stuff with X being a number? So it might be a duplicate of #111

**Comment by mickym2** [comment] 2020-07-10 22:04
So i use between 150-160 iobroker out nodes. So I am not even able to assign the 15 log entries above to the 15 nodes which probably caused the error. I have no idea - how to gind this out. I checked all - and they use all objects under normal adapters. 
90% of the nodes write under 0_userdata.0 objects.

There is only one node - where the topic is set via a msg. But the I deactivated and activated this node and restarted the adapter. The error remains. 

Turning off and on the autoCreate is false if I specify: Ignore messages for non existing stated - autoCreate is true if I specify: Create states if not exist.

So in my opinion both should work. But I have no idea - as all 150 nodes are configured as autoCreate= false, but only 15 cause this info message in the log

**Closed** 2020-10-17 20:01 UTC
Labels: wontfix
