### ISSUE TITLE
Change Default Setting of converting iobroker Data to Strings (Default should be no)

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#243] opened 2021-12-29 20:18 UTC
I am not sure why this setting is part of the adapter settings. 
May be it is to have similar behavior as  with mqtt in nodes. - In my opinion this should be not a default setting or this setting can be removed from the adapter settings at all.
So default should be that data types should keep their type as defined. 

Instead there is place to put other options in the adapter - like http-static path or other settings.js options.

If - especially beginners - do not change this setting, they have to check and change all flows, which are triggered by iobroker states.

**Comment by jwiesel** [comment] 2022-01-02 13:19
Thanks for raising that topic @mickym2 !
I've been using the Node-Red adapter for quite some time and wasn't really aware of the setting in general. I always wondered, why I had to interpret string-values in Node-Red when getting data from ioBroker nodes.
Changing the default setting would be easy (https://github.com/ioBroker/ioBroker.node-red/blob/c09acb7cb7384dd8659142664726572b316acedf/io-package.json#L318).
But I am not sure, if changing the default might impact existing installations, where users didn't set the parameter explicitly?!

**Comment by mickym2** [comment] 2022-01-02 13:33
Sorry closing was by accident. 

> But I am not sure, if changing the default might impact existing installations, where users didn't set the parameter explicitly?!

Without reading the current settings,  s.o. who updates the adapter and has set the conversion on will have a problem and has to set the setting again. On the other side how many install the adapter new and start to convert all values within the flow. I always tell them to switch off this. 

I do not know if the update procedure can read if the setting is already on - and dependent on if the setting is on or not the setting can be taken over or not. So then nothing would change for existing installations but conversion will be switched off for new installations.

**Comment by jwiesel** [comment] 2022-01-03 11:17
I just created a PR in case we go for it.
@Apollon77 , @GermanBluefox : What are your thoughts on this?
Will the settings of an existing instance change on adapter update, if default settings are changed?
If not, changing the default should not be an issue. If yes, users might need to rework their flows in Node-Red.

**Comment by Apollon77** [comment] 2022-01-03 11:43
Die not had time to look into it. The settings file is newly updated out of the template on each adapter start. This means that new settings should be backward compatible or else we break it for users. We can add settings in the adapter to allow setting new stuff accordingly for the users that want that.

So are the new defaults you added backward compatible?

**Comment by Apollon77** [comment] 2022-01-03 11:46
Aaahhh ignore my last answer. I thought you mean the node-red settings file. 

Adapter wise changed defaults will only have effect for new instances. All other users need to adjust it manually

**Comment by jwiesel** [comment] 2022-01-03 12:10
ok great! Thanks for the swift response!
@mickym2 : Let's test #253  :) Install URL: https://github.com/jwiesel/ioBroker.node-red/archive/refs/heads/defaultValueConvertSetting.zip

**Comment by mickym2** [comment] 2022-01-03 19:00
> ok great! Thanks for the swift response! @mickym2 : Let's test #253 :) Install URL: https://github.com/jwiesel/ioBroker.node-red/archive/refs/heads/defaultValueConvertSetting.zip

I tried to install from the URL on a fresh test system. 

Everything looked OK

`<html>
<body>


host.MWDebian | 2022-01-03 18:38:45.527 | info | iobroker exit 0
-- | -- | -- | --
host.MWDebian | 2022-01-03 18:38:44.434 | info | iobroker upload [0] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/bcrypt.min.js bcrypt.min.js application/javascript
host.MWDebian | 2022-01-03 18:38:44.339 | info | iobroker upload [1] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/de/translations.json i18n/de/translations.json application/json
host.MWDebian | 2022-01-03 18:38:44.285 | info | iobroker upload [2] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/en/translations.json i18n/en/translations.json application/json
host.MWDebian | 2022-01-03 18:38:44.197 | info | iobroker upload [3] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/es/translations.json i18n/es/translations.json application/json
host.MWDebian | 2022-01-03 18:38:44.142 | info | iobroker upload [4] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
host.MWDebian | 2022-01-03 18:38:44.087 | info | iobroker upload [5] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/it/translations.json i18n/it/translations.json application/json
host.MWDebian | 2022-01-03 18:38:44.029 | info | iobroker upload [6] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
host.MWDebian | 2022-01-03 18:38:43.974 | info | iobroker upload [7] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
host.MWDebian | 2022-01-03 18:38:43.919 | info | iobroker upload [8] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
host.MWDebian | 2022-01-03 18:38:43.863 | info | iobroker upload [9] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
host.MWDebian | 2022-01-03 18:38:43.772 | info | iobroker upload [10] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
host.MWDebian | 2022-01-03 18:38:43.711 | info | iobroker upload [11] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index.html index.html text/html
host.MWDebian | 2022-01-03 18:38:43.654 | info | iobroker upload [12] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index_m.html index_m.html text/html
host.MWDebian | 2022-01-03 18:38:43.599 | info | iobroker upload [13] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/node-red.png node-red.png image/png
host.MWDebian | 2022-01-03 18:38:43.522 | info | iobroker upload [14] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/words.js words.js application/javascript
host.MWDebian | 2022-01-03 18:38:39.000 | info | iobroker 787 \| (node::addon_register_func) (regfunc), \ \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’ 821 \| NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) \| ^~~~~~~~~~~~~../src/bcrypt_node.cc:359:1: note: in expansion of macro ‘NODE_MODULE’ 359 \| NODE_MODULE(bcrypt_lib, init); \| ^~~~~~~~~~~
host.MWDebian | 2022-01-03 18:38:38.999 | info | iobroker In file included from ../../nan/nan.h:54, from ../src/bcrypt_node.cc:1:../src/bcrypt_node.cc: At global scope:/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:787:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
host.MWDebian | 2022-01-03 18:38:38.954 | info | iobroker In file included from ../src/bcrypt_node.cc:1:../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:../../nan/nan.h:2298:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 2298 \| , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete) \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
host.MWDebian | 2022-01-03 18:38:32.842 | info | iobroker 787 \| (node::addon_register_func) (regfunc), \ \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’ 821 \| NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) \| ^~~~~~~~~~~~~../src/bcrypt_node.cc:378:1: note: in expansion of macro ‘NODE_MODULE’ 378 \| NODE_MODULE(bcrypt_lib, init); \| ^~~~~~~~~~~
host.MWDebian | 2022-01-03 18:38:32.841 | info | iobroker In file included from ../node_modules/nan/nan.h:53, from ../src/bcrypt_node.cc:1:../src/bcrypt_node.cc: At global scope:/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:787:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
host.MWDebian | 2022-01-03 18:38:32.787 | info | iobroker ../node_modules/nan/nan.h:2232:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] 2232 \| , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete) \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
host.MWDebian | 2022-01-03 18:38:32.786 | info | iobroker In file included from ../src/bcrypt_node.cc:1:../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
host.MWDebian | 2022-01-03 18:37:37.680 | info | iobroker npm install jwiesel/ioBroker.node-red#refs/heads/defaultValueConvertSetting --loglevel error --prefix "/opt/iobroker" (System call)
host.MWDebian | 2022-01-03 18:37:37.679 | info | iobroker NPM version: 6.14.15
host.MWDebian | 2022-01-03 18:37:37.290 | info | iobroker install jwiesel/ioBroker.node-red#refs/heads/defaultValueConvertSetting
host.MWDebian | 2022-01-03 18:37:35.746 | info | iobroker url https://github.com/jwiesel/ioBroker.node-red/archive/refs/heads/defaultValueConvertSetting.zip --host MWDebian


</body>
</html>`

**BUT no instance was created!!**

When I installed it a second time from the URL, it was faster but no instance was created:

`<html>
<body>


host.MWDebian | 2022-01-03 19:53:37.016 | info | iobroker exit 0
-- | -- | -- | --
host.MWDebian | 2022-01-03 19:53:35.905 | info | iobroker upload [0] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/bcrypt.min.js bcrypt.min.js application/javascript
host.MWDebian | 2022-01-03 19:53:35.851 | info | iobroker upload [1] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/de/translations.json i18n/de/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.797 | info | iobroker upload [2] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/en/translations.json i18n/en/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.742 | info | iobroker upload [3] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/es/translations.json i18n/es/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.688 | info | iobroker upload [4] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.627 | info | iobroker upload [5] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/it/translations.json i18n/it/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.571 | info | iobroker upload [6] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.517 | info | iobroker upload [7] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.461 | info | iobroker upload [8] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.405 | info | iobroker upload [9] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.348 | info | iobroker upload [10] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
host.MWDebian | 2022-01-03 19:53:35.279 | info | iobroker upload [11] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index.html index.html text/html
host.MWDebian | 2022-01-03 19:53:35.220 | info | iobroker upload [12] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/index_m.html index_m.html text/html
host.MWDebian | 2022-01-03 19:53:35.159 | info | iobroker upload [13] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/node-red.png node-red.png image/png
host.MWDebian | 2022-01-03 19:53:35.077 | info | iobroker upload [14] node-red.admin /opt/iobroker/node_modules/iobroker.node-red/admin/words.js words.js application/javascript
host.MWDebian | 2022-01-03 19:53:06.862 | info | iobroker npm install jwiesel/ioBroker.node-red#refs/heads/defaultValueConvertSetting --loglevel error --prefix "/opt/iobroker" (System call)
host.MWDebian | 2022-01-03 19:53:06.861 | info | iobroker NPM version: 6.14.15
host.MWDebian | 2022-01-03 19:53:06.466 | info | iobroker install jwiesel/ioBroker.node-red#refs/heads/defaultValueConvertSetting
host.MWDebian | 2022-01-03 19:53:04.889 | info | iobroker url https://github.com/jwiesel/ioBroker.node-red/archive/refs/heads/defaultValueConvertSetting.zip --host MWDebian


</body>
</html>`

**Comment by mickym2** [comment] 2022-01-03 19:05
Ok and I see that default is now - that default for a new instance is OFF by default. :)

**Comment by mickym2** [comment] 2022-01-03 19:10
http-Static is still not included in this version - correct?

**Comment by jwiesel** [comment] 2022-01-04 09:50
Thanks for testing! I just tested, that setting will not be changed in previously existing instances. As Apollon77 already confirmed. --> No impact on upgrade. --> No breaking change :)

As this enhancement does not change the default IP-Address or Port, your screenshot might be a separate issue. Unfortunately I couldn't reproduce it. 
![snap](https://user-images.githubusercontent.com/11034083/148040663-df00380b-1fc3-468a-bd3d-b13a06c524c1.png)


Regarding httpStatic: Each enhancement can be developed & tested individually in git. When results are successful, individual enhancements can be merged into the main version, which is rolled out to users later on. You can test the httpStatic enhancement, if you install it via the URL in #252 .

**Comment by Apollon77** [comment] 2022-03-11 22:47
Released in 3.0.0

**Closed by Apollon77** 2022-03-11 22:47 UTC
Labels: fixed
